name: institute_chat
description: Minimal chat app for an institute with attachments
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.2.0
  file_picker: ^8.1.2
  image_picker: ^1.1.2
  uuid: ^4.4.2

flutter:
  uses-material-design: true
